apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnpg-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-ui.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
