// Package api contains the request/response types and server interface for the
// CNPG Web UI REST API. These types mirror the OpenAPI spec in api/openapi.yaml.
//
// NOTE: Normally these types and the ServerInterface would be generated by
// oapi-codegen. They are hand-written here because oapi-codegen is not
// installed in this environment. Run `make generate` once oapi-codegen is
// available to replace this file with the generated version.
package api

import "encoding/json"

// ── Status ────────────────────────────────────────────────────────────────────

// NormalizedStatus is the four-value status enum exposed by the API.
// It abstracts CNPG Cluster phase strings into a stable set of values.
type NormalizedStatus string

const (
	// StatusHealthy means the cluster is running normally.
	StatusHealthy NormalizedStatus = "HEALTHY"
	// StatusTransient means a temporary, expected operation is in progress.
	StatusTransient NormalizedStatus = "TRANSIENT"
	// StatusFault means the cluster is in an error state.
	StatusFault NormalizedStatus = "FAULT"
	// StatusHibernated means the cluster has been paused/hibernated.
	StatusHibernated NormalizedStatus = "HIBERNATED"
)

// ── Error ─────────────────────────────────────────────────────────────────────

// ErrorCode is the machine-readable error category string.
type ErrorCode string

const (
	CodeNotFound   ErrorCode = "NOT_FOUND"
	CodeUnauth     ErrorCode = "UNAUTHORIZED"
	CodeForbidden  ErrorCode = "FORBIDDEN"
	CodeConflict   ErrorCode = "CONFLICT"
	CodeValidation ErrorCode = "VALIDATION_ERROR"
	CodeInternal   ErrorCode = "INTERNAL_ERROR"
)

// APIError is the canonical error response body. All 4xx/5xx responses use it.
// JSON field names match the OpenAPI spec: {error, code, details?}.
type APIError struct {
	Error   string          `json:"error"`
	Code    ErrorCode       `json:"code"`
	Details json.RawMessage `json:"details,omitempty"`
}

// ── Auth ──────────────────────────────────────────────────────────────────────

// LoginRequest is the body for POST /api/v1/auth/login.
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// LoginResponse is the body returned by a successful login.
type LoginResponse struct {
	Token    string `json:"token"`
	Username string `json:"username"`
}

// ChangePasswordRequest is the body for PUT /api/v1/auth/password.
type ChangePasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

// ── Cluster ───────────────────────────────────────────────────────────────────

// ClusterSummary is the lightweight cluster representation for list endpoints.
type ClusterSummary struct {
	Name           string           `json:"name"`
	Namespace      string           `json:"namespace"`
	Instances      int              `json:"instances"`
	ReadyInstances int              `json:"readyInstances"`
	Status         NormalizedStatus `json:"status"`
	Phase          string           `json:"phase,omitempty"`
	CurrentPrimary string           `json:"currentPrimary,omitempty"`
}

// ClusterDetail extends ClusterSummary with full spec fields.
type ClusterDetail struct {
	ClusterSummary
	StorageSize string `json:"storageSize,omitempty"`
	PgVersion   int    `json:"pgVersion,omitempty"`
	ImageName   string `json:"imageName,omitempty"`
	CreatedAt   string `json:"createdAt,omitempty"`
}

// CreateClusterRequest is the body for POST /api/v1/clusters.
type CreateClusterRequest struct {
	Name        string `json:"name"`
	Namespace   string `json:"namespace,omitempty"`
	Instances   int    `json:"instances"`
	StorageSize string `json:"storageSize"`
	PgVersion   int    `json:"pgVersion,omitempty"`
	ImageName   string `json:"imageName,omitempty"`
}

// ScaleClusterRequest is the body for PATCH /api/v1/clusters/{name}/scale.
type ScaleClusterRequest struct {
	Instances int `json:"instances"`
}

// UpdateClusterRequest is the body for PUT /api/v1/clusters/{name}.
// Only fields present (non-zero) in the request are applied.
type UpdateClusterRequest struct {
	Instances   int    `json:"instances,omitempty"`
	StorageSize string `json:"storageSize,omitempty"`
	ImageName   string `json:"imageName,omitempty"`
}

// ── Backup ────────────────────────────────────────────────────────────────────

// BackupSummary represents a single Backup CR.
type BackupSummary struct {
	Name        string `json:"name"`
	ClusterName string `json:"clusterName"`
	Phase       string `json:"phase"`
	StartedAt   string `json:"startedAt,omitempty"`
	StoppedAt   string `json:"stoppedAt,omitempty"`
	Method      string `json:"method,omitempty"`
}

// TriggerBackupRequest is the optional body for POST /api/v1/clusters/{name}/backups.
type TriggerBackupRequest struct {
	Method string `json:"method,omitempty"`
}

// ScheduledBackupSummary represents a ScheduledBackup CR.
type ScheduledBackupSummary struct {
	Name        string `json:"name"`
	ClusterName string `json:"clusterName"`
	Schedule    string `json:"schedule"`
	Immediate   bool   `json:"immediate,omitempty"`
	Suspended   bool   `json:"suspended,omitempty"`
}

// CreateScheduledBackupRequest is the body for POST /api/v1/clusters/{name}/scheduled-backups.
type CreateScheduledBackupRequest struct {
	Name      string `json:"name"`
	Schedule  string `json:"schedule"`
	Immediate bool   `json:"immediate,omitempty"`
}

// ── Pooler ────────────────────────────────────────────────────────────────────

// PoolerSummary represents a Pooler CR (read-only).
type PoolerSummary struct {
	Name         string `json:"name"`
	ClusterName  string `json:"clusterName"`
	Type         string `json:"type"`
	Instances    int    `json:"instances"`
	PoolMode     string `json:"poolMode,omitempty"`
	MaxClientConn int   `json:"maxClientConn,omitempty"`
}

// ── Postgres Config ───────────────────────────────────────────────────────────

// PgParamMetadata describes a single Postgres configuration parameter.
type PgParamMetadata struct {
	Name           string `json:"name"`
	Type           string `json:"type"`
	CurrentValue   string `json:"currentValue"`
	DefaultValue   string `json:"defaultValue,omitempty"`
	RequiresRestart bool  `json:"requiresRestart"`
}

// PgConfigResponse is returned by GET and PUT /api/v1/clusters/{name}/postgres-config.
type PgConfigResponse struct {
	Parameters      []PgParamMetadata `json:"parameters"`
	RequiresRestart bool              `json:"requiresRestart"`
}

// UpdatePgConfigRequest is the body for PUT /api/v1/clusters/{name}/postgres-config.
type UpdatePgConfigRequest struct {
	Parameters map[string]string `json:"parameters"`
}
